# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{firstfm}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aleksandr Lossenko"]
  s.date = %q{2010-03-10}
  s.description = %q{Firstfm is a ruby wrapper for the Last.fm APIs ( http://www.last.fm/api ). My main focus is to import events from Last.FM, but with time I will try to add support for all API methods.}
  s.email = %q{aleksandr @nospam@ cligs.ee}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/firstfm.rb",
     "lib/firstfm/event.rb",
     "lib/firstfm/geo.rb",
     "lib/firstfm/location.rb",
     "lib/firstfm/venue.rb"
  ]
  s.homepage = %q{http://github.com/egze/firstfm}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A ruby wrapper for the Last.fm APIs}
  s.test_files = [
    "test/test_helper.rb",
     "test/unit/geo_test.rb",
     "test/unit/venue_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<will_paginate>, [">= 2.3.12"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.2"])
    else
      s.add_dependency(%q<will_paginate>, [">= 2.3.12"])
      s.add_dependency(%q<httparty>, [">= 0.5.2"])
    end
  else
    s.add_dependency(%q<will_paginate>, [">= 2.3.12"])
    s.add_dependency(%q<httparty>, [">= 0.5.2"])
  end
end

